### ISSUE TITLE
Add Inverse Cumulative Probability as an option

### ISSUE THREAD

**Issue by damonhook** [damonhook/warcry-statshammer#22]
Often, it can be more relevant to know to probability of causing at least `W` wounds, rather than knowing the probability of causing no more than `W` wounds. I'd prefer to have `P(X>=W)` shown rather than `P(X<=W)`.

**Comment by Spoofardio** [comment]
I added a PR for this: https://github.com/damonhook/warcry-statshammer/pull/42 (I think this is what you wanted)

**Comment by damonhook** [comment]
This has been released with version [v0.5.0](https://github.com/damonhook/warcry-statshammer/releases/tag/v0.5.0)
Thanks @Spoofardio
