### ISSUE TITLE
duplicate fighter button

### ISSUE THREAD

**Issue by apathyward** [damonhook/warcry-statshammer#41]
itd be great to be able to duplicate a fighter profile in the stats calculator. it could just be a Copy icon next to the Trash icon.

**Comment by Spoofardio** [comment]
I added a PR for this: https://github.com/damonhook/warcry-statshammer/pull/42

**Comment by damonhook** [comment]
This has been released with version [v0.5.0](https://github.com/damonhook/warcry-statshammer/releases/tag/v0.5.0)
Thanks @Spoofardio
